name: Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.2'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Enable Maintenance Mode (Upload Maintenance PHP)
      uses: bayssmekanique/action-simple-file-upload@v2
      with:
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        host: ${{ secrets.FTP_SERVER }}
        src: public/maintenance.php
        dest: ${{ secrets.BASE_PATH }}/public/index.php
        secure: true
        verbose: true

    - name: Install Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

    - name: 📂 Deploy Source Files # Deploys ./ 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.main.json
          exclude: |
            **/.git*/**
            **/public/**
            **/storage/**
            **/vendor/**
            **/storage/**
            **/CHANGELOG.md
            **/README.md
            **/config.php
            **/LICENSE
            **/install.bat
            **/update.bat
 
    - name: 📂 Deploy Assets # Deploys /public
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.assets.json
          exclude: |
            **/.git*/**
            **/storage/**
            **/sync-state/**
            **/vendor/**
            **/.editorconfig
            **/.nginx.conf
            **/CHANGELOG.md
            **/composer.json
            **/composer.lock
            **/config.php
            **/extend.php
            **/flarum
            **/LICENSE
            **/README.md
            **/site.php
            **/install.bat
            **/update.bat
            **/public/maintenance.php

    - name: 📂 Deploy Storage # Deploys /storage
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.storage.json
          exclude: |
            **/.git*/**
            **/sync-state/**
            **/public/**
            **/storage/cache/**
            **/vendor/**
            **/.editorconfig
            **/.nginx.conf
            **/CHANGELOG.md
            **/composer.json
            **/composer.lock
            **/config.php
            **/extend.php
            **/flarum
            **/LICENSE
            **/README.md
            **/site.php
            **/install.bat
            **/update.bat

    - name: 📂 Deploy Vendor Files # Deploys /vendor
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.vendor.json
          exclude: |
            **/.git*/**
            **/public/**
            **/storage/**
            **/sync-state/**
            **/.editorconfig
            **/.nginx.conf
            **/CHANGELOG.md
            **/composer.json
            **/composer.lock
            **/config.php
            **/extend.php
            **/flarum
            **/LICENSE
            **/README.md
            **/site.php
            **/install.bat
            **/update.bat

    - name: Disable Maintenance Mode (Upload Public Index PHP)
      uses: bayssmekanique/action-simple-file-upload@v2
      with:
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        host: ${{ secrets.FTP_SERVER }}
        src: public/index.php
        dest: ${{ secrets.BASE_PATH }}/public/index.php
        secure: true
        verbose: true